### ISSUE TITLE
multigit --status fails on yet not cloned repositories

### ISSUE THREAD

**Issue by jmnavarrol** [jmnavarrol/python-multigit#6]
Running `multigit --status` when a repository defined within the subrepos file is not yet cloned throws an uncontrolled exception:
```sh
$ multigit --status
INFO: no valid 'subrepos' file found at '/home/jmnav/REPOS/python-multigit/src':
INFO: processing git repository rooted at '/home/jmnav/REPOS/python-multigit':
Traceback (most recent call last):
  File "/home/jmnav/.virtualenvs/multigit-development/bin/multigit", line 8, in <module>
    sys.exit(main())
  File "/home/jmnav/REPOS/python-multigit/src/multigit/__init__.py", line 50, in main
    my_subrepos.process(os.getcwd(), report_only=args.status)
  File "/home/jmnav/REPOS/python-multigit/src/multigit/subrepos.py", line 118, in process
    current_subrepo = self.__process_subrepo(current_subrepo, report_only)
  File "/home/jmnav/REPOS/python-multigit/src/multigit/subrepos.py", line 255, in __process_subrepo
    local_commit = repo.commit().hexsha
UnboundLocalError: local variable 'repo' referenced before assignment
$
```

This should be properly controlled.

**Comment by jmnavarrol** [comment]
Closed on **v0.10.5**.
