### ISSUE TITLE
crash on local existant, remote non-existant branch

### ISSUE THREAD

**Issue by jmnavarrol** [jmnavarrol/python-multigit#9]
When subrepos requests a branch that exists locally but can't be found anymore at remote, it throws uncontrolled errors:

**When the current local branch is the same as the requested one:**
```python
Traceback (most recent call last):
  File "[redacted]/bin/multigit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "[redacted]/python-multigit/src/multigit/__init__.py", line 53, in main
    my_subrepos.process(os.getcwd(), report_only=args.status)
  File "[redacted]/python-multigit/src/multigit/subrepos.py", line 98, in process
    current_subrepo = git_subrepo.update(current_subrepo)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/python-multigit/src/multigit/gitrepo.py", line 133, in update
    repostatus = self.status(repoconf)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/src/multigit/gitrepo.py", line 107, in status
    desired_commit = str(repo.commit(remote_ref))
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/.virtualenvs/multigit-development/lib/python3.11/site-packages/git/repo/base.py", line 536, in commit
    return self.rev_parse(str(rev) + "^0")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/.virtualenvs/multigit-development/lib/python3.11/site-packages/git/repo/fun.py", line 229, in rev_parse
    obj = cast(Commit_ish, name_to_object(repo, rev[:start]))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/.virtualenvs/multigit-development/lib/python3.11/site-packages/git/repo/fun.py", line 163, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref 'origin/test-branch' did not resolve to an object
```

**When the current local branch is different to the requested branch (which also exists locally but not remotely):**
```python
Traceback (most recent call last):
  File "[redacted]/.virtualenvs/multigit-development/bin/multigit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "[redacted]/python-multigit/src/multigit/__init__.py", line 53, in main
    my_subrepos.process(os.getcwd(), report_only=args.status)
  File "[redacted]/python-multigit/src/multigit/subrepos.py", line 98, in process
    current_subrepo = git_subrepo.update(current_subrepo)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/python-multigit/src/multigit/gitrepo.py", line 196, in update
    repo.git.pull()
  File "[redacted]/multigit-development/lib/python3.11/site-packages/git/cmd.py", line 638, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/.virtualenvs/multigit-development/lib/python3.11/site-packages/git/cmd.py", line 1183, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[redacted]/.virtualenvs/multigit-development/lib/python3.11/site-packages/git/cmd.py", line 983, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull
  stderr: 'There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> test-branch
'
 ```

These should be controlled errors instead.

**Comment by jmnavarrol** [comment]
[Version v0.11.5](https://github.com/jmnavarrol/python-multigit/tree/v0.11.5) should solve this issue.
